### ISSUE TITLE
Chybný výpočet P^tilde v implementaci LM-IEKF

### ISSUE THREAD

**Issue by JakubVanek** [vtfanta/Soft-Constrained-Kalman-Filter#1]
Dobrý den,

narazil jsem na překlep v implementaci LM-IEKF v tomto repozitáři: vyskytuje se tu maticová inverze na špatném místě. Když srovnám rovnici pro Ptilde v článku https://ieeexplore.ieee.org/document/7266781
![obrazek](https://github.com/vtfanta/Soft-Constrained-Kalman-Filter/assets/6003171/c440d698-c7d4-49e4-95f1-2b73abd7bab8)

s implementací

https://github.com/vtfanta/Soft-Constrained-Kalman-Filter/blob/219598fc2c99d3caf805d53ab8f8b5e3f34a05dd/ExtendedFiltering/src/data_updates.jl#L106

tak mi přijde, že velká závorka by v inverzi být neměla.

Backstory je tato: mám na letním projektu na DCE implementovat IEKF s řízením délky kroku do jednoho Matlab/Simulink toolboxu. Kvůli struktuře toolboxu zvažuji, jestli by v mém případě nebylo jednodušší místo řízení délky kroku řídit jenom tlumení v Levenberg-Marquardtovi (pokud to chápu dobře, tak pak bych nepotřeboval pro datový krok IEKF dvě vnořené smyčky, ale jen jednu). Chtěl jsem proto vyzkoušet, jak se LM-IEKF chová v porovnáním s IEKF-L popsaným v článku. Skript se mi ale choval zvláštně - i pro velké hodnoty μᵢ (resp. λ) se hodnota V(x) nezlepšovala.

Jakub Vaněk

**Comment by JakubVanek** [comment]
Re: backstory -- nakonec se mi LM-IEKF podařilo v Julii rozchodit i bez line-searche, což byl můj cíl. Přikládám zdrojový kód, pokud by se to někomu hodilo.
```julia
# Iterated extended Kalman filter Levenberg-Marquardt data update with damping parameter control
function data_update_iekf_lm_wernercontrol(se0::StateEstimate{S}, meas_srcs, λ0::T=1e0,
    ϵ = 1e-3, maxiter = 30) where {S<:Real,T<:Real}

    function step(prev_step::StateEstimate{S}, se0, meas_srcs, λᵢ)
        x̂ᵢ = prev_step.x̂
        Pᵢ = prev_step.P

        function V(x::Vector, se::StateEstimate{T}, meas_srcs)
            Σ = BlockDiagonals.BlockDiagonal([m.Σ for m in meas_srcs])
            h = vcat([m.output_fun(StateEstimate(x, se.P)) for m in meas_srcs]...)
            z = vcat([m.z for m in meas_srcs]...)

            first_term = z - h
            second_term = se.x̂ - x

            first_term' / Σ * first_term + second_term' / se.P * second_term
        end

        Σ = BlockDiagonals.BlockDiagonal([m.Σ for m in meas_srcs])
        H = vcat([m.∇output_fun(se0) for m in meas_srcs]...)
        h = vcat([m.output_fun(se0) for m in meas_srcs]...)
        z = vcat([m.z for m in meas_srcs]...)

        B = Diagonal(H' / Σ * H + inv(se0.P))
        P̃ = (I(length(x̂ᵢ)) - se0.P * (se0.P + 1/λᵢ * inv(B))^(-1)) * se0.P
        K = P̃ * H' / (H * P̃ * H' + Σ)

        Δ = se0.x̂ - x̂ᵢ + K * (z - h - H * (se0.x̂ - x̂ᵢ)) - λᵢ * (I(length(x̂ᵢ)) - K * H) * P̃ * B * (se0.x̂ - x̂ᵢ)

        V0 = V(x̂ᵢ, se0, meas_srcs)
        V1 = V(x̂ᵢ + Δ, se0, meas_srcs)

        if V1 <= V0
            x̂ᵢ₊₁ = x̂ᵢ + Δ
            Pᵢ₊₁ = (I(length(x̂ᵢ)) - K * H) * se0.P
            λᵢ₊₁ = λᵢ / 2
        else
            x̂ᵢ₊₁ = x̂ᵢ
            Pᵢ₊₁ = Pᵢ
            λᵢ₊₁ = λᵢ * 10
        end

        StateEstimate(x̂ᵢ₊₁, Pᵢ₊₁), λᵢ₊₁, Δ
    end

    iter = 1
    prev_est = se0
    next_est = nothing
    prev_λ = λ0
    next_λ = nothing
    while iter < maxiter
        next_est, next_λ, Δ = step(prev_est, se0, meas_srcs, prev_λ)
        iter += 1
        if LinearAlgebra.norm(Δ) < ϵ
            break
        end
        prev_est = next_est
        prev_λ   = next_λ
    end
    next_est
end
```

**Comment by vtfanta** [comment]
Jo, už to vidím. Napsal jsem zpětné lomítko místo hvězdičky:( Používal jsem téměř jen toho Gausse-Newtona, tak jsem si tohoto nevšiml. Snad tam podobná chyba není. Jestli to chápu dobře, tak ten postup bez line-search je, že při zlepšení kritéria v rámci iterace se λᵢ₊₁ zmenší (LM se blíží GN) a jinak zvětší (LM se blíží gradientní metodě).

**Comment by vtfanta** [comment]
Teď jsem to přepsal v hlavní větvi. Můžu uzavřít issue, nebo vidíte ještě něco?

**Comment by JakubVanek** [comment]
Děkuji moc, teď už mi tam přijde všechno OK; to řízení tlumení v LM chápu stejně.
